In [56]:
import pandas as pd
import numpy as np

In [57]:
df=pd.read_csv('Customer_Behaviour.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [59]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [60]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [61]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [62]:
df.duplicated().sum()

0

In [63]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [64]:
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [65]:
scaler=StandardScaler()
df[['Age', 'EstimatedSalary']]=scaler.fit_transform(df[['Age', 'EstimatedSalary']])
df.head()

    User ID  Gender       Age  EstimatedSalary  Purchased
0  15624510       1 -1.781797        -1.490046          0
1  15810944       1 -0.253587        -1.460681          0
2  15668575       0 -1.113206        -0.785290          0
3  15603246       0 -1.017692        -0.374182          0
4  15804002       1 -1.781797         0.183751          0

In [66]:
# y=f(x)
# Split features(x) and Target variable(y)  
x=df[['Gender','Age', 'EstimatedSalary']]
y=df['Purchased']

In [67]:
# Split dataset
from sklearn.model_selection import train_test_split

In [68]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2, random_state=10, stratify=y)
ytrain.head()

71     0
68     0
104    0
219    1
49     0
Name: Purchased, dtype: int64

In [69]:
from sklearn.naive_bayes import GaussianNB

In [70]:
model=GaussianNB()

In [71]:
model.fit(xtrain,ytrain)

GaussianNB()

In [99]:
ypred=model.predict(xtest)
xtest

     Gender       Age  EstimatedSalary
31        0 -1.017692         1.975007
47        0 -1.017692        -0.462276
108       1 -1.113206         0.477399
109       0  0.032952         0.301210
272       1  2.134241        -0.814655
..      ...       ...              ...
190       1 -1.304232         0.418669
246       0 -0.253587        -0.579736
135       1 -1.399745        -0.197993
79        0 -1.113206        -1.548776
205       0  0.892570        -0.667830

[80 rows x 3 columns]

In [73]:
ytest

31     1
47     0
108    0
109    0
272    1
      ..
190    0
246    0
135    0
79     0
205    0
Name: Purchased, Length: 80, dtype: int64

In [74]:
from sklearn.metrics import accuracy_score, confusion_matrix
a=accuracy_score(ypred,ytest)*100
a

95.0

In [75]:
cm=confusion_matrix(ypred,ytest)
cm

array([[48,  1],
       [ 3, 28]], dtype=int64)

In [109]:
gen=int(input("Enter Gender:"))
age=int(input("Enter age:"))
sal=int(input("Enter Salary:"))

Enter Gender: 0
Enter age: 25
Enter Salary: 30000

In [111]:
new_val=model.predict([[gen,age,sal]])
new_val

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [113]:
for i in range(0,79):
    print(ypred[i],"---->",ytest[i])

1 ----> 0

KeyError: 1

In [115]:
ytest

31     1
47     0
108    0
109    0
272    1
      ..
190    0
246    0
135    0
79     0
205    0
Name: Purchased, Length: 80, dtype: int64