In [496]:
import numpy as np
import pandas as pd

In [497]:
df=pd.read_csv('iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [498]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [499]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [500]:
from sklearn.preprocessing import LabelEncoder

In [501]:
le=LabelEncoder()
df['Species']=le.fit_transform(df['Species'])
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [502]:
# y=f(x)
x=df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',	'PetalWidthCm']]
y=df['Species']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [503]:
from sklearn.model_selection import train_test_split

In [504]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y, test_size=0.2, random_state=42, stratify=y)
xtest

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
38             4.4           3.0            1.3           0.2
127            6.1           3.0            4.9           1.8
57             4.9           2.4            3.3           1.0
93             5.0           2.3            3.3           1.0
42             4.4           3.2            1.3           0.2
56             6.3           3.3            4.7           1.6
22             4.6           3.6            1.0           0.2
20             5.4           3.4            1.7           0.2
147            6.5           3.0            5.2           2.0
84             5.4           3.0            4.5           1.5
107            7.3           2.9            6.3           1.8
141            6.9           3.1            5.1           2.3
104            6.5           3.0            5.8           2.2
51             6.4           3.2            4.5           1.5
7              5.0           3.4            1.5           0.2
49             5.0           3.3            1.4           0.2
14             5.8           4.0            1.2           0.2
69             5.6           2.5            3.9           1.1
63             6.1           2.9            4.7           1.4
138            6.0           3.0            4.8           1.8
10             5.4           3.7            1.5           0.2
140            6.7           3.1            5.6           2.4
58             6.6           2.9            4.6           1.3
134            6.1           2.6            5.6           1.4
132            6.4           2.8            5.6           2.2
77             6.7           3.0            5.0           1.7
75             6.6           3.0            4.4           1.4
18             5.7           3.8            1.7           0.3
116            6.5           3.0            5.5           1.8
28             5.2           3.4            1.4           0.2

In [505]:
from sklearn.neighbors import KNeighborsClassifier

In [506]:
model=KNeighborsClassifier(n_neighbors=5, weights='distance', metric='sqeuclidean')

In [507]:
model.fit(xtrain,ytrain)

KNeighborsClassifier(metric='sqeuclidean', weights='distance')

In [508]:
ypred=model.predict(xtest)
ypred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 2, 2, 1, 1, 0, 2, 0])

In [509]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [510]:
a=accuracy_score(ytest,ypred)*100
a

100.0

In [511]:
cm=confusion_matrix(ytest,ypred)
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]], dtype=int64)